### PR TITLE
Switch from Persona to OKTA for auth

### PR DESCRIPTION
**Pull request by pmac**

### CODE REVIEW

**Comment by pmac** [comment]
@glogiotatidis r?

**Comment by pmac** [comment]
FYI @jgmize @bensternthal

**Comment by jgmize** [comment]
@pmac will you please deploy this to staging?

**Comment by jgmize** [comment]
@pmac will you also please reply here with a link to the bug(s) for activating the staging and prod apps?

**Comment by pmac** [comment]
So... staging huh... Are you sure such a thing exists? I'm not aware of one. I could create one if you want.

Also this isn't useful until we hear back from the okta team and get the metadata file for the specific instance. Each "app" on okta has a specific full URL to callback to, and so far I was only planning on setting this up for prod.

**Comment by pmac** [comment]
Also we've not filed said bugs yet because we need to setup a config in the testing OKTA instance that we can reference in the bug so they can copy it to prod. Will update here once we have it.

Thanks for project-managing, but I think we've got it.

**Comment by glogiotatidis** [comment]
OK this was tested on oktastaging and works fine, nice work @pmac  👍 r+ 

I filed [bug 13717969](https://bugzilla.mozilla.org/show_bug.cgi?id=1317969) for the InfraOps to create the staging and prod apps in real Okta and provide us with the metadata files. Once we've got them we can update this PR and merge.

**Comment by jgmize** [comment]
thanks @pmac and @glogiotatidis :)

**Comment by pmac** [comment]
Metadata files added. Merging. Should be on stage shortly. Thanks!

**Comment by pmac** [comment]
Oh snap! 🐍 Staging instance is deployed and Okta login worked for me! Give it a test when you can:

https://nucleus-stage.us-west.moz.works/admin/

**Comment by jgmize** [comment]
I just logged into stage. Nice work :)

**Comment by glogiotatidis** [comment]
wfm too! 👍

**Pull request merged**
