### PR TITLE
Add new 'Reviewed by release manager' flag on Release - for Nucleus-side information only

### LINKED ISSUE #788: Add a Review Checkbox on Release pages
Relman peer review release notes. 
It would be useful to have a checkbox that relman can check to indicate they reviewed a specific release

### PR DESCRIPTION
**Pull request by stevejalim**
The relman team wanted a way to mark a release as 'reviewed by a manager' or not in Nucleus. 

This changeset adds a new field which tracks that. I went with a null=True BooleanField to avoid having to backfill any data

The field, reviewed_by_release_manager, will appear in JSON API data, but Bedrock will skip it because it doesn't map to a field known by Bedrock. (And this is fine - we don't need to think about it in Bedrock)

Screenshot 2023-11-20 at 14 00 09

Resolves #788

### CODE REVIEW

**Comment by pmac** [comment]
so this field doesn't affect whether it's published or not?

**Comment by stevejalim** [comment]
> so this field doesn't affect whether it's published or not?

@pmac Correct - it's just a way to avoid wasted work or waiting for people to review when they have reviewed, I believe

**Comment by stevejalim** [comment]
Here's the bedrock side code that reads the JSON - it won't die if it meets a key in the data that doesn't feature in the Bedrock-side model: https://github.com/mozilla/bedrock/blob/654fb1da00566444c5783fb770a7fd67f1f36259/bedrock/releasenotes/models.py#L128-L135

**Comment by pmac** [comment]
👍 r+

**Pull request merged**
